const ProjectPermissions = Object.freeze({
    UPDATE_PROJECT: "update_project",
    DELETE_PROJECT: "delete_project",
    ARCHIVE_PROJECT: "archive_project",
    ADD_WORKFLOW: "add_workflow",
    UPDATE_WORKFLOW: "update_workflow",
    DELETE_WORKFLOW: "delete_workflow",
    ADD_ACTOR: "add_actor",
    UPDATE_ACTOR_ROLE: "update_actor_role",
    REMOVE_ACTOR: "remove_actor",
    ADD_SPRINT: "add_sprint",
    UPDATE_SPRINT: "update_sprint",
    DELETE_SPRINT: "delete_sprint",
    ADD_ISSUE_TYPE: "add_issue_type",
    UPDATE_ISSUE_TYPE: "update_issue_type",
    DELETE_ISSUE_TYPE: "delete_issue_type",
    ADD_ISSUE: "add_issue",
    UPDATE_ISSUE: "update_issue",
    DELETE_ISSUE: "delete_issue",
    ADD_COMMENT: "add_comment",
    UPDATE_COMMENT: "update_comment",
    DELETE_COMMENT: "delete_comment",
    ADD_ROLE: "add_role",
    UPDATE_ROLE: "update_role",
    DELETE_ROLE: "delete_role",
});

export default ProjectPermissions;
